<?php
include "header.php";
?><br><br><br><br><br><br><br>

<h1 id="feat">Privacy policy</h1><br><br>
<p class="dictum">Upholding the privacy of our clients is an immensely important concern for . This privacy policy governs our collection, processing, use, and storage of your personal information for internal use only. By using the website .com or its subdomains or by using its mobile applications (“Website(s)”), you consent to’s privacy policy and data practices. We may periodically make changes to the Privacy Policy. Your use of the Website and/or mobile apps following the change in the Privacy Policy signifies that you accept and agree to our Policies.</p>
<br>
<p class="dictum">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
<br><br>
<p class="map">Interpretation</p>
<p class="dictum">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
<br><br><br>
<p class="map">Definitions</p>
<p class="dictum">For the purposes of this Privacy Policy:</p>
<ul style="disk" class="elit">
<li class="amet">Account means a unique account created for You to access our Service or parts of our Service.
<li class="amet">Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li><br>
<li class="amet">Application means the software program provided by the Company downloaded by You on any electronic device, named </li><br>
<li class="amet">Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Technologies Pvt Ltd, 2nd floor, Gurudas Building, Opp Axis Bank ATM, S S Puram Main Road, Tumkur - 572102, India</li><br>
<li class="amet">Country refers to India</li><br>
<li class="amet">Device means any device that can access the Service such as and not limited to a computer, a cellphone, or a digital tablet.</li><br>
<li class="amet">Personal Data is any information that relates to an identified or identifiable individual.</li><br>
<li class="amet">Service refers to the Application, website or any service or products provided under the name of.</li><br>
<li class="amet">Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li><br>
<li class="amet">Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li><br>
<li class="amet">You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li><br>
</ul><br><br><br><br>
<p class="map">Collecting and Using Your Personal Data</p><br><br>

<p class="dictum">will collect your personal information for opening an account and also for your transactions while using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally, identifiable information may include, but is not limited to:</p>
<ul style="disk" class="elit">
<li class="amet">Email address</li><br>
<li class="amet">PAN Card Details</li><br>
<li class="amet">First name and last name</li><br>
<li class="amet">Phone number</li><br>
<li class="amet">Adderess, State, Province, ZIP/Postal code, City</li><br>
<li class="amet">Usage Data</li><br></ul><br><br>
<p class="map">Usage Data</p><br><br>
<p class="dictum">Usage Data is collected automatically when using the Service.</p><br>

<p class="dictum">While for the purpose of your transactions, we will keep track of your Bank Details and information pertaining to your IP address and device or computer used by You for the purpose.</p><br>

<p class="dictum"> will further use your personal information to process transactions</p><br>

<p class="dictum">To send periodic emails, notifications, and SMS with updates, promotions, company news, and notices regarding changes to policies. To customize, measure, and improve Service, including the content and layout of our Website and mobile applications. To analyze the use of the Website and mobile applications. To prevent potentially prohibited or illegal activities. To undertake a verification of your identity with third-party electronic identification providers.</p><br>

<p class="dictum">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p><br>

<p class="dictum">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p><br>

<p class="dictum">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p><br><br>

<p class="map">Information Collected while Using the Application</p><br><br>
<p class="dictum">While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</p>
<ul style="disk" class="elit">
<li class="amet">Information regarding your location</li><br>
<li class="amet">Pictures and other information from your Device's camera and photo library</li><br>
<li class="amet">Contacts</li><br>
<li class="amet">Storage</li><br></ul><br><br>
<p class="dictum">We use this information to provide features of Our Service to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.</p>

<p class="dictum">No personal information of any user is being disclosed for any purpose. Stored personal information is available only to the user for editing purposes and to customer service personnel, the verification department and to administrators and consultants, and third-party entities and service providers who are bound by non-disclosure agreements.</p>

<p class="dictum">However, we do share information with law enforcement and government officials when we are compelled to do so by a court order or similar legal procedure and/or entity.</p>

<p class="dictum">You also agree that shall be free to transfer/disclose any information shared by you with us, to a related party or to an affiliate or to any entity controlled by the promoters of. We may also transfer your information during the sale of assets or business to another company or demerger into another company or while getting acquired by another company or getting merged with another company.</p>

<p class="map">Changing your Personal Information
You may access your personal information in order to make changes or corrections by visiting Account Settings -> Settings. However, when you change any personal information, you will need to provide the documents again and go through the needed verification procedure before your changes come into effect.

<p class="map">Use of Your Personal Data</p>
<p class="dictum">The Company may collect Personal Data for the following purposes:
<ul style="disk" class="elit">
<li class="amet">To provide and maintain our Service, including to monitor the usage of our Service.</li><br>
<li class="amet">To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li><br>
<li class="amet">For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li><br>
<li class="amet">To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as and not limited to a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li><br>
<li class="amet">To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
<li class="amet">To manage Your requests: To attend and manage Your requests to Us.</li><br>
<li class="amet">For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li><br>
<li class="amet">For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our Service, products, services, marketing, and your experience.</li></ul><br>
<p class="dictum">We may share Your personal information in the following situations:</p>
<ul style="disk" class="elit">
<li class="amet">With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li><br>
<li class="amet">For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li><br>
<li class="amet">With Affiliates: We may share Your information with Our Affiliates, in which case we will require those Affiliates to honor this Privacy Policy. Affiliates include and are not limited to Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li><br>
<li class="amet">With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.</li><br>
<li class="amet">With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li><br>
<li class="amet">With Your consent: We may disclose Your personal information for any other purpose with Your consent.</li></ul><br><br>
<p class="map">Retention of Your Personal Data</p>
<p class="dictum">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>

<p class="dictum">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p><br><br>

<p class="map">Transfer of Your Personal </p>
<p class="dictum">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>

<p class="dictum">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>

<p class="dictum">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p><br><br>

<p class="map">Disclosure of Your Personal Data</p><p class="map"></p>Business Transactions
<p class="dictum">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p><br><br>

<p class="map">Law enforcement</p>
<p class="dictum">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p><br><br>

<p class="map">Other legal requirements</p>
<p class="dictum">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p><br>

<ul style="disk" class="elit">
<li class="amet">Comply with a legal obligation</li><br>
<li class="amet">Protect and defend the rights or property of the Company</li><br>
<li class="amet">Prevent or investigate possible wrongdoing in connection with the Service</li><br>
<li class="amet">Prevent or investigate possible wrongdoing in connection with the Service</li><br>
<li class="amet">Protect against legal liability</li></ul><br><br>
<p class="map">Security of Your Personal Data</p>
<p class="dictum">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

<p class="map">Links to Other Websites</p>
<p class="dictum">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>

<p class="dictum">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

<p class="map">Changes to this Privacy Policy</p>
<p class="dictum">We may update Our Privacy Policy from time to time. We will perform decent efforts to notify You of any changes by posting the new Privacy Policy on this page.</p>

<p class="dictum">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>

<p class="dictum">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

<p class="map">Cookies</p>
<p class="dictum">We may also place cookies on your device while you access the Website. In this regard, we use flask cookies to promote account security, as well as both session and persistent cookies. Any sensitive information in these cookies is encoded so that only can interpret the information stored on them. The cookies are placed for the following purposes:</p>
<p class="dictum">If you have any questions about this Privacy Policy, You can contact us:</p>
<ul style="disk" class="elit">
<li class="amet">Recognize you as a customer;</li><br>
<li class="amet">Collect information about your computer to mitigate risk and help prevent fraud;</li><br>
<li class="amet">Customize your experience, content, and advertising;</li><br>
<li class="amet">Measure promotional effectiveness;</li><br>
<li class="amet">While  will attempt to notify you of these changes, it is your responsibility to review this privacy policy on regular basis and remain informed and updated of any changes.</li></ul><br><br>
<p class="map">Acceptanct of Privacy Policy</p>
<p class="dictum">By using the Online Platforms and/or any services provided by, you signify your acceptance of this Privacy Policy and terms of service. If you do not agree to this Privacy Policy or terms of service, please do not use the Online Platforms or any services provided by . Your continued use of the Online Platforms following the posting of changes to this Privacy Policy will be deemed your acceptance of those changes</p>

<p class="map">Contact Us</p>
<p class="dictum">If you have any questions about this Privacy Policy, You can contact us:</p>
<ul style="disk" class="elit">
<li class="amet">By email: support@crytozz.com</li><br>
<li class="amet">By call: +91 76538-98342</li></ul>

<?php
include "footer.php";
?>