<?php
include "header.php";
?><br><br><br><br><br><br><br>
 
 
 <h1 id="feat">Terms Of Service</h1><br><br>
<p class="dictum">By using the websites .com and/or its subdomains and/or its mobile applications (“Website(s)”), and further by registering to avail the services offered by the Website, Mobile Wallet and Mobile Exchange(“Service”), you hereby agree to accept and comply with the terms and conditions of use stated below (“Terms of Use”). You should read, agree, and accept the entire Terms of Use prior to your use of this Website or any of the Service. You are hereby expressly barred from accessing the Website or availing of the Service unless you agree and accept these Terms of Use.</p>
<p class="dictum">As used herein, “ and/or Company” refers to the holding company of being Technologies Private Limited (‘Company’), a private limited company incorporated under the laws of India and having its registered office on 2nd floor, Gurudas Building, S.S. Puram Main Road, Tumkur, India - 572102 its owners, directors, investors, employees or other related parties. Where the context so permits, depending upon the context, “” may also refer to the services, products, website, content or other materials (collectively, “Materials”) provided by the Company.</p><br><br>

<p class="map">Service</p><br>
<p class="dictum">The Service operated by the Company in the name of  allows buyers (“Buyers”) and sellers (“Sellers”) to buy and sell Bitcoin (for more information on Bitcoin, please refer to http://www.bitcoin.org) and other crypto assets (collectively called Crypto Assets).The Service provided by  also allows all registered users of the Service (“Members”) to:</p><br>
<ol  class="elit">
<li class="amet">Transfer crypto assets to other Members or other users of Crypto Assets outside the Website</li><br>
<li class="amet">Send and receive Crypto Assets</li><br>
<li class="amet">Purchase and Sell Crypto Assets</li><br>
<li class="amet">Use Crypto Assets for availing loan.</li><br></ol>
<p class="dictum">It is possible that the laws in the country where the user resides do not allow the usage of an online tool with the characteristics of Crypto Assets or any of its features.  does not encourage the violation of any laws and cannot be held responsible for violation of such laws. It is your responsibility to follow the laws of your country of residence and/or country from which you access this Website and the Service. As long as you agree to and comply with these Terms of Use, grants to you a personal/business, non-exclusive, non-transferable, non-sublicensable, and limited right to enter and use the Website and the Service.</p><br><br>

<p class="map">Taxes</p><br>
<p class="dictum">It is your responsibility to determine, collect, report, and submit any taxes applicable to the payments you make or receive in connection with the use of the Website and the Service to the appropriate tax authority. is not responsible for determining whether taxes apply to your transaction or for collecting, reporting or remitting any taxes arising from any transaction unless explicitly mentioned. As per the new Income Tax regulations, some of the transactions made will be subject to TDS deductions and rate applicable will be as per your TDS Declaration in your profile settings.</p><br><br>
<p class="map">Identity verification</p><br>
<p class="dictum">To comply with AML/KYC recommendations, we require our clients to verify their identity by providing scanned copies* of the following**:</p><br>
<ol  class="elit">
<li class="amet">PAN card (mandatory)</li><br>
<li class="amet">Photo identity - Aadhaar card or driving license)</li><br>
<li class="amet">Selfie photo (mandatory))</li><br><br></ol>
<p class="dictum">*Copies should be in colour and have a good resolution.<br>
** The above documents provided by the clients shall be kept on the server safely, and the Company shall not disclose the same to any third party unless we are mandated to do so under the provisions of any applicable laws.<br>
 may use your personal information:</p>
<ol  class="elit">
<li class="amet">To identify you.</li><br>
<li class="amet">To process transactions.</li><br>
<li class="amet">To send periodic emails with updates, promotions, company news, and notices regarding changes to policies.</li><br>
<li class="amet">Customise, measure, and improve Service and the content and layout of our Website and applications.</li><br>
<li class="amet">To analyse the use of the Website.</li><br>
<li class="amet">Prevent potentially prohibited or illegal activities.</li><br>
<li class="amet">To undertake a verification of your identity with third party electronic identification providers.</li><br></ol>
<p class="dictum">Notwithstanding anything contained in these terms of use, the Company shall be free to transfer/ disclose any information shared by you with the Company, to a related party or to an affiliate or to any entity controlled by the promoters of. We may also transfer your information during the sale of assets or business to another company, de-merger into another company while getting acquired by another company or getting merged with another company.<br>
By opening an account to use the Service (“Account”), you expressly represent and warrant that:</p>
<ol  class="elit">
<li class="amet">You have accepted these Terms of Use.</li><br>
<li class="amet">You do have read and understood the information provided by the Website through its How-it-works and Resources section.</li><br>
<li class="amet">You are at least 18 years of age and have the full capacity to accept these Terms of Use and enter into a transaction involving Bitcoin or other Crypto Assets.</li><br><br></ol>
<p class="map">Cryptoassets</p>
<ol  class="elit">
<li class="amet">Cryptoassets like “Bitcoin” are merely software, as reflected in the relevant blockchain and in the public addresses of Users, that creates a digital asset, which is not regulated by any central authority and has no independent existence.</li><br>
<li class="amet">The price or value of such Crypto Assets is not set or regulated by any central or governmental authorities.</li><br>
<li class="amet">Crypto Assets may not even have an identified creator</li><br>
<li class="amet"> only offers a platform to users for rendering the Services set out herein and performs only the role of an intermediary. does not advise on the purchase or sale of any Crypto Asset, does not guarantee returns from any investment or transactions, and does not itself buy or sell any of the Crypto Assets that are made available for purchase or sale by Users on the platform.</li><br>
<li class="amet">Users are cautioned against speculative investments in Crypto Assets in the light of the above and are directed to avail these services, including purchase or sale of Crypto Assets or investing therein, upon fully understanding the technology that has created Crypto Assets and subject to the risks that arise from such an unregulated asset, which only exists in digital form.</li><br><br></ol>

<p class="map">Limitations On Use Of Services</p><br>
<ol  class="elit">
<li class="amet"> offers a platform for trading in Crypto Assets through the Platform. Presently the platform offers to trade in Bitcoin & some Crypto Assets, although the Services may extend to other Crypto Assets as well in the future (for which all of the terms contained herein will apply). is neither the creator nor the administrator of any Crypto Assets, including Bitcoin and is not in any way responsible for the global pricing of any Crypto Assets, the operation of any blockchain with respect to any Crypto Assets, or the mining process in relation to any Crypto Assets. It merely facilitates the trading in Crypto Assets by Users on the  platform and does not engage in such trading itself or buy or sell any Crypto Assets for its own account or for its own benefit. has no control over the generation, distribution, retention (except in its wallets), verification, termination, or market volatility of any Crypto Assets. It merely acts as an intermediary for the trading in Crypto Assets by User and provides other ancillary services in relation thereto, which are more fully set out hereunder.</li><br>
<li class="amet"> does not provide any warranty of any kind, either express or implied, in relation to the Services. The Services and the products offered therein, including facilitation services for the trading of Crypto Assets between Users, are provided on an “as-is” and “as available” basis. Users avail of the Services and deal in Crypto Assets at their own risk and with full awareness of the risk of the possible diminishment, devaluation and (potentially) complete loss of the entire holding or valuation of the User Account and all Crypto Assets held therein, in the event of the occurrence of any of the risk factors outlined in this Agreement (as well as other risk factors inherent in any transactions involving Crypto Assets), including, but not limited to, changes in the regulatory or legal regime in India and/or outside India, and any legal, regulatory, contractual or other restrictions that may be placed on. It is hereby expressly declared that offers no warranty of any kind regarding the Services.</li><br>
<li class="amet"> Services are strictly available for use only within India or for Indians, to the extent (and till such time) that transactions or trading in Crypto Assets are permitted and not been curtailed in such parts of India. In the event that a User resides in any such jurisdiction within India where any transactions in Crypto Assets may be prohibited (“Prohibited Jurisdiction”), Users are not permitted to use the Services in any form (“Prohibited Jurisdiction Use”). Any Prohibited Jurisdiction Use will amount to a breach of this Agreement, and shall forthwith be entitled to terminate this Agreement and the use and operation of the relevant User Account, shall extend all cooperation to the relevant governmental and enforcement authorities, and shall not be liable in any manner whatsoever for any loss arising out of such, in relation to, or subsequent to such Prohibited Jurisdiction Use. Users are therefore duly warned against availing of the Services in any manner whatsoever in or from a Prohibited Jurisdiction, or from anywhere outside India if the jurisdiction does not support the use of and/or Services. Users shall be solely responsible for ensuring compliance with this requirement and for compliance with the laws and regulations of the jurisdiction in or from where they are availing of the  Services. Subject to confirmation by the User to be bound by the terms contained herein and compliance with the terms contained herein at all times,  hereby grants to the User a personal/business, revocable, non-exclusive, non-transferable, non-sublicensable, and limited right to use the Services.</li><br>
<li class="amet">Users are hereby duly cautioned that presently in India, ‘virtual currencies’(including all Crypto Assets) have not been recognised or authorised as a medium for payment, as a commodity for trade, or in any form, by the central bank, monetary authority, or governmental or regulatory body in India. The Reserve Bank of India (“RBI”) has currently issued three press releases viz. dated 24th December 2013, 1st February 2017 and 5th December 2017 respectively, cautioning users, holders and traders against the use of, and trading in, virtual currencies. Later in April 2018, RBI restricted all entities regulated by RBI to not provide services to crypto assets dealing individuals/companies which was later overturned by the Honourable Supreme Court on the 4th of March 2020. Users shall therefore avail of the Services subject to the above caution issued by the RBI and should be aware of the regulatory and financial risks inherent in dealing with Crypto Assets in any manner.</li><br>
<li class="amet"> may use third-party service providers to render some or all of the Services or to facilitate the same. User agrees to the use of such third parties and hereby provides consent for the collection, analysis, use, dissemination and retention by such third parties of any and all personal data, or sensitive personal data and information, of the User. User shall be bound by the terms of service of such third parties to the same extent as would be bound. shall, however, not be responsible or liable for any act, inaction, commission or omission by such third parties, including with respect to data protection, privacy, security practices, or compliance with applicable laws and regulations with respect thereto, including (but not limited to) the Information Technology Act 2000.</li><br>
<li class="amet">These terms shall be applicable to all existing and new Users. reserves the right to modify or amend the terms herein, and possibly an intimation thereof shall be sent to existing Users, who may decide to opt-out of the Services at such time by intimating of such intention in writing. Continued use of the Services shall be deemed to amount to confirmation and acceptance of the modified or altered terms hereof.</li><br>
<li class="amet">The Parties agree that the terms set out hereunder are in consideration of good and valuable consideration and shall be and are intended to be binding on both Parties.</li><br><br></ol>

<p class="map">Limited Right of Use</p>
<p class="dictum">Unless otherwise specified, all Materials on this Website are the property of the Company and are protected by copyright, trademark, and other applicable laws. You may view, print, and/or download a copy of such Materials on any single computer solely for your personal, informational, non-commercial use, provided you keep intact all copyright and other proprietary notices.<br>
The trademarks, service marks, and logos of and others used in this Website (“Trademarks”) are the property of the Company and its respective owners. The software, text, images, graphics, data, prices, trades, charts, graphs, video, and audio used on this Website belong to Company. The Trademarks and Materials should not be copied, reproduced, modified, republished, uploaded, posted, transmitted, scraped, collected or distributed in any form or by any means, whether manual or automated. The use of any such Materials on any other website or networked computer environment for any other purpose is strictly prohibited; any such unauthorised use may violate copyright, trademark, and other applicable laws and could result in criminal or civil legal actions and penalties.</p><br><br>


<p class="map">Indemnity</p>
<ol  class="elit">
<li class="amet">To the full extent permitted by applicable law, you hereby agree to indemnify, and its affiliates, officers, directors, agents, employees, and suppliers against any action, liability, cost, claim, loss, damage, proceeding or expense suffered or incurred if direct or not directly arising from your use of the Website, Service, or from your violation of these Terms of Use.</li><br>
<li class="amet"> shall indemnify the User and hold harmless against and in respect of any losses incurred or suffered by the User solely due to any proven wilful and malicious act or default on the part of. This indemnity is subject to the representations and warranties set out hereinabove, i.e., shall not be liable for any losses arising out of risks or consequences set out in the representations and warranties, which have been read, acknowledged and understood by the User by virtue of their use of the Services, or for actions initiated by against User for suspension, cancellation or termination of their User Account for any reason. The liability of, in any event, shall be limited to the amounts actually received from the User, in INR, or INR 1,00,000 whichever is lower as consideration for the services rendered by in relation to the transaction to which the indemnity claim relates. If the claim does not relate to any transaction in particular, then’s liability shall be limited to the amounts actually received from the User, in INR, or INR 1,00,000, whichever is lower as consideration for the services rendered by in relation to the three transactions immediately preceding the date on which the claim is made by the User.</li><br>
<li class="amet">These provisions shall survive the expiration or termination of this Agreement</li><br><br></ol>
<p class="map">Miscellaneous</p>
<p class="dictum">If we are unable to perform the Service outlined in the Terms of Use due to factors beyond our control, including but not limited to an event of force majeure, change of law or change in sanctions policy, we will not have any liability to you with respect to the Service provided under these Terms of Use and for a time period coincident with the event.</p><br><br>

<p class="map">Modification of Terms</p>
<p class="dictum"> reserves the right to change, add or remove portions of these Terms of Use, at any time, in an exercise of its sole discretion. You may be notified of any changes in advance through your Account inbox. Upon such notification, it is your responsibility to review the amended Terms of Use. Your continued use of the Website and Service following the changes to the Terms of Use signifies that you have accepted and agreed to such changes and that all subsequent transactions by you will be subject to the amended Terms of Use.</p><br><br>

<p class="map">Contact Us</p>
<p class="dictum">If you have any questions relating to these Terms of Use, your rights and obligations arising from these Terms of Use and/or your use of the Website and the Service, your Account, or any other matter, please contact us at support@cryptozz.com</p><br><br>

<p class="map">Lending Service Usage</p>
<p class="dictum">These terms apply to you when you use our lending service provided by the Company. No provision herein shall constitute investment or loan advice or consultation, and in no way shall any of the Parties view Lending Service as an investment advisor or a loan intermediary. The customer confirms that they understand and accept that the Lending Platform creates an opportunity for him/her to enter into loan agreements and use cryptoassets as collateral for the said agreements.</p>

<ol  class="elit">
<li class="amet">The minimal amount of the Collateral to be provided shall be calculated on the basis of the Loan-To-Value ratio (hereinafter LTV). LTV is usually 50%. This information is displayed to you at the time of taking a loan. The company is entitled to change this rate at any time, and it will be effective for subsequent loans.</li><br>
<li class="amet">When you are applying for the loan, you will be given some of the choices like payment date of the month (in case of EMI) which will be binding on you once your loan is approved. The received loan may either be in crypto assets or in fiat currency as chosen by you or displayed to you when you are applying for the loan.</li><br>
<li class="amet">The User shall add cryptoasset funds into the joint lending account to increase the collateral to avoid liquidation in case the price of collateral drops.</li><br>
<li class="amet">All the payments you need to make towards the loan should be made to your loan account. The payment of EMIs/interests/fee/penalties/principal is automatically paid from your loan account to your loan.</li><br>
<li class="amet">The User takes the responsibility to pay the EMIs (Easy Monthly Installments) or interest payments in a timely manner, failing which the user will be subject to additional fees/penalties/interests as mentioned to you when you are applying for the loan.</li><br>
<li class="amet">The Company reserves the right to liquidate a part of the collateral or full collateral at the prevailing rates on the website to settle EMIs, fees, penalties, interests, principal and any other monies due against the loan account.</li><br>
<li class="amet">While the Company does its best to avoid liquidation of your assets, the discretion of the Company will be final and binding.</li><br>
<li class="amet">In case the Company is undergoing restructuring, change of management or being transferred, then the Company reserves the right to ask the loan seekers to settle the loan accounts within 30 days from the time you have received your notice. The customers may be able to apply for a new loan later.</li><br><br></ol>


<?php
include "footer.php";
?>